# Generated by Django 2.0.2 on 2018-02-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='percent_complete',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='status',
            field=models.CharField(choices=[('CREATED', 'step one of searching'), ('RUNNING', 'step two of searching')], default='CREATED', max_length=64),
        ),
    ]
